### ISSUE TITLE
A working example?

### ISSUE THREAD

**Issue by aminya** [cprecioso/parcel-plugin-purgecss#55]
I want to use this plugin, but I cannot seem to be able to configure it. Is there an example somewhere? I need to use it with bootstrap.

This is my non-working code: https://github.com/aminya/solid-realworld/tree/purgecss

I included my styles in html here: https://github.com/aminya/solid-realworld/blob/d9e9f6c5dca671c6a578c1ec191881147d720dc0/index.html#L22

which imports bootstrap: https://github.com/aminya/solid-realworld/blob/purgecss/styles/styles.css

Ref.: https://github.com/ryansolid/solid-realworld/pull/4

**Comment by joshbedo** [comment]
Second this when I try to use it it's literally removing all CSS with React/Parcel.

**Comment by cprecioso** [comment]
Sorry for the delay.

@aminya Your code uses Parcel 2. This package was created for Parcel 1.

I don't think I will update this code. I don't use Parcel nor PurgeCSS anymore; and to be honest both project's documentation was so lacking that I had to discover much myself. I don't remember how this works, it's been 18 months since I coded it. I am archiving the project.
